sudo: required

services:
  - docker

language: java
dist: bionic

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

env:
  - TIMESTAMP=$(date '+%Y%m%d%H%M%S')
  - DOCKER_IMAGE=jmezna/rso-comments:1.0.0-SNAPSHOT-"${TIMESTAMP}"

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
